--Tablas
CREATE TABLE PROGRAMA (
                          id_programa DOUBLE PRIMARY KEY,
                          nombre VARCHAR(50) NOT NULL,
                          duracion DOUBLE NOT NULL,
                          registro DATE NOT NULL,
                          id_facultad DOUBLE NOT NULL
);

CREATE TABLE PERSONA (
                         id_persona DOUBLE PRIMARY KEY,
                         nombre VARCHAR(50) NOT NULL,
                         apellidos VARCHAR(50) NOT NULL,
                         email VARCHAR(128) NOT NULL,
                         tipo VARCHAR(10) NOT NULL,
                         codigo DOUBLE NULL,
                         id_programa DOUBLE NULL,
                         activo BOOLEAN NULL,
                         promedio DOUBLE NULL,
                         tipo_contrato VARCHAR(50) NULL
);

CREATE TABLE FACULTAD (
                          id_facultad DOUBLE PRIMARY KEY,
                          nombre VARCHAR(50) NOT NULL,
                          id_decano DOUBLE NOT NULL
);

CREATE TABLE CURSO (
                       id_curso INT PRIMARY KEY,
                       nombre VARCHAR(50) NOT NULL,
                       activo BOOLEAN NULL,
                       id_programa DOUBLE NOT NULL
);


CREATE TABLE INSCRIPCION (
                             id_inscripcion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             id_curso INT NOT NULL,
                             anio INT NOT NULL,
                             semestre INT NOT NULL,
                             id_estudiante DOUBLE NOT NULL
);


CREATE TABLE CURSO_PROFESOR (
                                id_curso_profesor INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                id_profesor DOUBLE NOT NULL,
                                anio INT NOT NULL,
                                semestre INT NOT NULL,
                                id_curso INT NOT NULL
);

--Relaciones

ALTER TABLE PERSONA
    ADD CONSTRAINT fk_persona_programa FOREIGN KEY (id_programa) REFERENCES PROGRAMA(id_programa);

ALTER TABLE FACULTAD
    ADD CONSTRAINT fk_facultad_decano FOREIGN KEY (id_decano) REFERENCES PERSONA(id_persona);

ALTER TABLE PROGRAMA
    ADD CONSTRAINT fk_programa_facultad FOREIGN KEY (id_facultad) REFERENCES FACULTAD(id_facultad);

ALTER TABLE CURSO
    ADD CONSTRAINT fk_curso_programa FOREIGN KEY (id_programa) REFERENCES PROGRAMA(id_programa);

ALTER TABLE INSCRIPCION
    ADD CONSTRAINT fk_inscripcion_curso FOREIGN KEY (id_curso) REFERENCES CURSO(id_curso);

ALTER TABLE INSCRIPCION
    ADD CONSTRAINT fk_inscripcion_estudiante FOREIGN KEY (id_estudiante) REFERENCES PERSONA(id_persona);

ALTER TABLE CURSO_PROFESOR
    ADD CONSTRAINT fk_curso_profesor_profesor FOREIGN KEY (id_profesor) REFERENCES PERSONA(id_persona);

ALTER TABLE CURSO_PROFESOR
    ADD CONSTRAINT fk_curso_profesor_curso FOREIGN KEY (id_curso) REFERENCES CURSO(id_curso);